/*
 * File: app/view/Form.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JWF.view.Form', {
    extend: 'Ext.Panel',

    config: {
        id: 'newJogContainer',
        layout: {
            type: 'card'
        },
        scrollable: false,
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'New Jog',
                items: [
                    {
                        xtype: 'button',
                        id: 'addRunBackBtn',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        id: 'addFriendsBtn',
                        align: 'right',
                        hidden: true,
                        text: 'Add'
                    }
                ]
            },
            {
                xtype: 'container',
                padding: '15 15 15 15',
                items: [
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'locationField',
                                placeHolder: 'Where?'
                            },
                            {
                                xtype: 'textfield',
                                id: 'distanceField',
                                placeHolder: 'How Many Miles?'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'component',
                                id: 'selectedFriends',
                                hidden: true
                            },
                            {
                                xtype: 'button',
                                id: 'addFriendsButton',
                                margin: 5,
                                ui: 'add-friends',
                                text: 'Add Friends'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'addRunButton',
                        ui: 'facebook',
                        text: 'Add Jog'
                    }
                ]
            },
            {
                xtype: 'list',
                id: 'friendsList',
                store: 'Friends',
                itemTpl: '{name}',
                mode: 'MULTI'
            }
        ]
    }
});